fix: pin lancedb to avoid breaking change 0.25.0 (#276)
0.25 introduces a new library that conflicts with our version of sqlglot.

+ lance-namespace-urllib3-client==0.

failure happens when installing on collab notebooks.

```Downloading lance_namespace_urllib3_client-0.2.1-py3-none-any.whl (228 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.5/228.5 kB 21.7 MB/s eta 0:00:00
Installing collected packages: types-protobuf, sqlglot, pymupdf, jmespath, scikit-learn, botocore, s3transfer, lance-namespace-urllib3-client, json-schema-to-pydantic, lance-namespace, boto3, lancedb, fenic
  Attempting uninstall: sqlglot
    Found existing installation: sqlglot 25.20.2
    Uninstalling sqlglot-25.20.2:
      Successfully uninstalled sqlglot-25.20.2
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.6.1
    Uninstalling scikit-learn-1.6.1:
      Successfully uninstalled scikit-learn-1.6.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 2.29.1 requires sqlglot<28.0.0,>=25.20.0, but you have sqlglot 28.0.0 which is incompatible.```